################################################################################
# \file bsp.mk
#
#
################################################################################
# \copyright
# Copyright 2021-2023 Cypress Semiconductor Corporation (an Infineon company) or
# an affiliate of Cypress Semiconductor Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

ifeq ($(WHICHFILE),true)
$(info Processing $(lastword $(MAKEFILE_LIST)))
endif

LIFE_CYCLE_STATE?=DM

#Flash build
DIRECT_LOAD=0

# Any additional components to apply when using this board.
BSP_COMPONENTS:=

# Any additional defines to apply when using this board.
BSP_DEFINES:=

# this is need for picking the secure/non secure Firmware image
ifeq ($(LIFE_CYCLE_STATE),DM)
BSP_COMPONENTS+=SM
else
BSP_COMPONENTS+=CM
endif

# App preferred execution memory
# use flash, psram, or ram
APPEXEC?=flash

# linker script template
BSP_LINKER_SCRIPT_PATH=$(MTB_TOOLS__TARGET_DIR)/TOOLCHAIN_$(TOOLCHAIN)
BSP_LINKER_SCRIPT=$(BSP_LINKER_SCRIPT_PATH)/$(CHIP_NAME)_$(APPEXEC).$(MTB_RECIPE__SUFFIX_LS)

# Select between the shared and dedicated LNA / ANT paths.
# The three options are SLNA_ANT0, DLNA_BTANT and DLNA_ANT0.
CHIP_ANT_SEL:=SLNA_ANT0

################################################################################
# ALL ITEMS BELOW THIS POINT ARE AUTO GENERATED BY THE BSP ASSISTANT TOOL.
# DO NOT MODIFY DIRECTLY. CHANGES SHOULD BE MADE THROUGH THE BSP ASSISTANT.
################################################################################

# Board device selection. MPN_LIST tracks what was selected in the BSP Assistant
# All other variables are derived by BSP Assistant based on the MPN_LIST.
MPN_LIST:=

# Device specific components picked up by pdl-cat5.mk file
DEVICE_COMPONENTS:=

-include $(SEARCH_mtb-pdl-cat5)/devices/pdl-cat5.mk

